#!/usr/bin/env sh

set -eu

# Install composer
curl -sS https://getcomposer.org/installer | php -- \
    --version=2.0.11 \
    --install-dir=/usr/local/bin \
    --filename=composer

# Install common and dev packages
apk add --no-cache \
    $PHPIZE_DEPS \
    git \
    openssh \
    vim

# Install pcov
mkdir -p /opt/php-libs  cd /opt/php-libs
git clone https://github.com/krakjoe/pcov.git /opt/php-libs/pcov
cd /opt/php-libs/pcov
phpize
./configure --enable-pcov
make
make install
docker-php-ext-enable pcov

# Install coveralls
wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.4.3/php-coveralls.phar -o /usr/local/bin/coveralls
chmod +x /usr/local/bin/coveralls

